INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Bob", 25);

INSERT INTO projects (title) VALUES ("HHRD");
INSERT INTO projects (title) VALUES ("HHRD");
INSERT INTO projects (title) VALUES ("HHRD");
INSERT INTO projects (title) VALUES ("HHRD");
INSERT INTO projects (title) VALUES ("HHRD");
INSERT INTO projects (title) VALUES ("HHRD");
INSERT INTO projects (title) VALUES ("HHRD");
INSERT INTO projects (title) VALUES ("HHRD");
INSERT INTO projects (title) VALUES ("HHRD");
INSERT INTO projects (title) VALUES ("HHRD");

INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
INSERT INTO pledges (amount) values (12);
